language: python

python:
    - 3.5.2
# install dependencies
install:
  - pip install -r requirements.txt
  - pip install coveralls

script:

  - nosetests run tests.py --with-coverage --cover-package=api


after_success:

  - coveralls
