language: python

services:
  - postgresql

python:
  - 3.5.2

postgres:
  adapter: postgresql
  database: hellobooks_test

# install dependencies
install:
  - pip install -r requirements.txt
  - pip install coveralls

script:
  - nosetests --with-coverage --cover-package=api

after_success:
  - coveralls

env:
  - DB=postgres

before_script:
  - psql -c 'CREATE DATABASE hellobooks_test;' -U postgres
