language: python

services:
  - postgresql

python:
  - 3.5.2

# install dependencies
install:
  - pip install -r requirements.txt
  - pip install coveralls

before_script:
  - psql -c 'create database hellobooks_test;' -U postgres

script:
  - nosetests --with-coverage --cover-package=api

after_success:
  - coveralls
