language: python

python:
    - 3.5.2
# install dependencies
install:
  - pip install -r requirements.txt
  - pip install coveralls

script:

  - nosetests modelstests.py --with-coverage

after_success:

  - coveralls