language: python

python:
    - 3.5.2
# install dependencies
install:
  -pip install -r requirements.txt

install:
  - pip install codecov

# run scripts
script:
  - coverage erase
  - coverage run models_tests.py && coverage html

after_success:
  - codecov
