language: python

python:
    - 2.7
    - 3.5
    - 3.6
# install dependencies
install:
  -pip install -r requirements.txt

install:
  - pip install codecov

# run scripts
script:
  - coverage erase
  - coverage run models_tests.py && coverage html

after_success:
  - codecov

# check style
script:
    - pylint --output-format=text run.py
