FORMAT: 1A

# Hello Books API Documentation

This a API Documentation for Hello Books Application. A simple application that helps manage a library and its processes like stocking, tracking and renting books.

# Group Books

## Books Collections [/api/v1/books]

### Add a New Book [POST /api/v1/books]

+ Request (application/json)

    {
        "title":"The Lean Startup",
        "author":"Eric Ries",
        "isbn":"8298748374"
    }
    
+ Response 201 (application/json)
    + Body
        {
            "Success": "Book Created Successfully"
        }

### Get All Books [GET /api/v1/books]
+ Response 200 (application/json)
    + Attributes
        - Books (array[Book])

### Get Individual Book[GET /api/v1/books/{id}]
+ Parameter
    + id: '1' - The id of the book

+ Response 200 (application/json)
    + Attributes
        - Include Book
        
### Update a Book [PUT /api/v1/books/Books/{id}]
+ Parameter
    + id = '1'
    
+ Request (application/json)
    {
        "title":"The Lean Startup",
        "author":"Eric Ries",
        "isbn":"6726376254"
    }

+ Response 200 (application/json)
    {
        'Message': 'Book Update Successful'
    }

### Delete A Book [DELETE /api/v1/books/{id}]
+ Response 200 (application/json)
    + Body
        {
            "Message":"Book Deleted Successfully"
        }

# Group Users 

## User Collections [/api/v1/users]

### Get all Users [GET /api/v1/users]
+ Response 200 (application/json)
    + Attributes
        - Users (array[User])

### Borrow Book [POST /api/v1/users/books/{id}]
+ Parameter
    + id = '1'

+ Response (application/json)
    + Body
        {
            'Message': 'Successfully Borrowed Book'
        }

# Group Auth 

## Auth Collections [/api/v1/auth]

### Add a User [POST /api/v1/auth/register]
+ Request (application/json)
    {
        "username":"dmwangi",
        "password":"password12345",
        "admin":"True"
    }

+ Response 200 (application/json)
    + Body
        {
            'Message': 'User Created Successfully'
        }

### Login [POST /api/v1/auth/login]
+ Request (application/json)
    {
        "username":"dmwangi",
        "password":"password12345"
    }

+ Response 200 (application/json)
    + Body 
        {
            "access_token":"--access-token--"
        }

### Reset User password [PUT /api/v1/auth/reset-password/{id}]
+ Parameter
    + id = '1'

+ Request (application/json)
    {
        "username":"dmwangi",
        "password":"password12345",
        "newpassword":"newpassword123"
    }

+ Response 200 (application/json)
    + Body
        {
            'Message': 'Password Reset Successful'
        }

### Logout [POST /api/v1/auth/logout]
+ Request 
    + Headers
        {
            "x-access-token":"--access-token--"
        }

+ Response 200 (application/json)
    + Body 
        {
            "Message":"Logged Out Successfully"
        }

# Data Structures
## Book (object)
- id: 1 (string) - The id of the book 
- title: The Lean Startup(string) - The title of the book
- author: Eric Ries (string) - The author of the book
- isbn: 8298748374 (string) - The ISBN number of the book

## User (object)
- id: 1 (string) - The id of the user
- username: dmwangi (string) - The user's username
- password: password12345 (string) - The user's password
- admin: True (string) - The user's admin status 
